[11:17 AM, 10/3/2019] Nag: pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

stages:
- stage: ARM-Build(DEV)
  steps:
  - task: AzurePowerShell@1
    inputs:
      azureSubscription: 'GTT1-PZI-GTUS-N-SUB005'
      ScriptPath: 'AzureResourceGroupDemo/Deploy-AzureResourceGroup.ps1'
      ScriptArguments: -ResourceGroupName 'demogroup' -ResourceGroupLocation 'centralus' 
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@2
    inputs:
      azureSubscription: 'GTT1-PZI-GTUS-N-SUB005'
      ScriptPath: 'AzureResourceGroupDemo/Deploy-AzureResourceGroup.ps1'
      ScriptArguments: -ResourceGroupName 'demogroup' -ResourceGroupLocation 'centralus' 
      azurePowerShellVersion: LatestVersion
  
  - task: AzurePowerShell@3
    inputs:
      azureSubscription: 'GTT1-PZI-GTUS-N-SUB005'
      ScriptPath: 'AzureResourceGroupDemo/Deploy-AzureResourceGroup.ps1'
      ScriptArguments: -ResourceGroupName 'demogroup' -ResourceGroupLocation 'centralus' 
      azurePowerShellVersion: LatestVersion